# Generated by Django 5.1.4 on 2025-01-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phnum', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
