# Generated by Django 5.1.4 on 2025-01-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='Usersignup',
        ),
    ]
