# Generated by Django 5.1.4 on 2025-01-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_signup_usersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busnumber', models.CharField(max_length=15)),
                ('routename', models.CharField(max_length=40)),
                ('departuretime', models.CharField(max_length=10)),
                ('arrivaltime', models.CharField(max_length=10)),
            ],
        ),
    ]
