# Generated by Django 5.1.4 on 2025-01-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_postbusinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBusContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactperson', models.CharField(max_length=30)),
                ('contactemail', models.EmailField(max_length=40)),
                ('contactphone', models.CharField(max_length=10)),
                ('contactaddress', models.CharField(max_length=30)),
            ],
        ),
    ]
