# Generated by Django 5.1.4 on 2025-01-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_postbuscontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostBusContact',
        ),
    ]
