# Generated by Django 5.1.4 on 2025-03-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_postbustype'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbusinfo',
            name='busfair',
            field=models.CharField(default='Pending..', max_length=5),
        ),
    ]
