# Generated by Django 5.1.4 on 2025-03-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_postbusinfo_busfair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbusinfo',
            name='busfair',
            field=models.CharField(max_length=5),
        ),
    ]
