# Generated by Django 5.1.4 on 2025-04-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_postbusinfo_busfair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busnumber', models.CharField(max_length=10)),
                ('travel_date', models.DateField(max_length=10)),
                ('numseats', models.CharField(max_length=10)),
            ],
        ),
    ]
